permalink: /:categories/:title/
url: "https://johnwevansjr.github.io/Website/"
full_name: "Saigon Jekyll Theme"
first_name: "Just"
last_name: "Me"
blog_title: "Title"
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "example"
copyright_year: "2016"
google_analytics_code: ""
aboutme: "I like ramen noodles with cream."
